server:
  port: 8092
spring:
  application:
    name: usian-content-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.80.135:7001
        - 192.168.80.135:7002
        - 192.168.80.135:7003
        - 192.168.80.135:7004
        - 192.168.80.135:7005
        - 192.168.80.135:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#大广告位图片信息
AD_CATEGORY_ID: 89
AD_HEIGHT: 240
AD_WIDTH: 670
AD_HEIGHTB: 240
AD_WIDTHB: 550

portal_ad_redis_key: portal_ad_redis_key