server:
  port: 8092
spring:
  application:
    name: usian-content-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/